### ISSUE TITLE
Use Disintegrate with images

### ISSUE THREAD

**Issue by adnanafzal565** [ZachSaucier/Disintegrate#2]
how to disintegrate an image using this library ?

**Comment by adnanafzal565** [comment]
thanks

**Comment by JaybeeGeek** [comment]
tried working with disintegrate with image: i have an image added on my html file and all i wanted it to do is to disintegrate on click but it didn't and when i checked my web console is was saying "disintegrate.init() not defined".  Do you have a solution to this 

I installed the disintegrate library using npm

**Comment by ZachSaucier** [comment]
I was able to get this working with passing `useCORS: true` as a part of the Disintegrate parameters. Adding it to the next version.
