### ISSUE TITLE
what does disintegrate.getDisObj(e.target) return

### ISSUE THREAD

**Issue by heyannu** [ZachSaucier/Disintegrate#5]

**Comment by ZachSaucier** [comment]
Hey Annu,

getDisObj returns the Disintegrate object for the given DOM element. So given a DOM element that has a Disintegrate object, it will return that object, which will look something like this:

`{"elem":{},"type":"simultaneous","actualWidth":400,"actualHeight":250,"lastWidth":400,"lastHeight":250,"count":0,"particleArr":[],"animationDuration":100,"canvas":{"class":"disParticleCanvas"},"ctx":{},"scrnCanvas":{},"scrnCtx":{},"ignoreColors":[],"isOutOfBounds":false,"isAnimating":false,"particleReductionFactor":111,"particleType":"ExplodingParticle","particleColor":[]}`
